In [1]:
from MFEA_lib.model import SMP_MFEA
from MFEA_lib.model.utils import *
from MFEA_lib.operators.Crossover import *
from MFEA_lib.operators.Mutation import *
from MFEA_lib.operators.Selection import *
from MFEA_lib.operators.Search import *
from MFEA_lib.tasks.Benchmark.Competitions import CEC17_benchmark, GECCO20_benchmark_50tasks, WCCI22_benchmark


##### Benchmark

In [2]:
# complex
ls_benchmark = []
ls_IndClass = []
name_benchmark = []
path = './RESULTS/result/WCCI22_complex/SMP_v2/'

for i in range(1, 11, 1):
# for i in [3, 6, 8, 10]:
    t, ic = WCCI22_benchmark.get_complex_benchmark(i)
    ls_benchmark.append(t)
    ls_IndClass.append(ic)
    name_benchmark.append(i)


In [2]:
# cec17
t, ic = CEC17_benchmark.get_10tasks_benchmark()

ls_benchmark = [t]
ls_IndClass = [ic]
name_benchmark = ["cec17"]

In [ ]:
# gecco20
ls_benchmark = []
ls_IndClass = []
name_benchmark = []
path = './RESULTS/result/GECCO20/SMP_v2/'

for i in range(1, 11, 1):
    t, ic = WCCI22_benchmark.get_50tasks_benchmark(i)
    ls_benchmark.append(t)
    ls_IndClass.append(ic)
    name_benchmark.append(i)

##### Code đơn

In [4]:
path = './RESULTS/result/CEC17_10tasks/SMP_KL/'

smpModel = MultiBenchmark(
    ls_benchmark= ls_benchmark,
    name_benchmark= name_benchmark,
    ls_IndClass= ls_IndClass,
    model= SMP_MFEA
)
smpModel.compile( 
    crossover = KL_SBXCrossover(nc= 2, u= 0.001, conf_thres= 1),
    # crossover = SBX_Crossover(nc = 2),
    mutation = PolynomialMutation(nm = 5, pm= 1),
    selection= ElitismSelection(random_percent= 0.1),
    search= L_SHADE(len_mem= 15),
    attr_tasks = ['crossover', 'mutation', 'search'],
)
smpModel.fit(
    nb_generations= 1000, nb_inds_each_task= 100, nb_inds_min= 20,
    lr = 0.1, p_const_intra= 0., prob_search = 0., lc_nums = 200,
    nb_epochs_stop= 1000, swap_po= False,
    evaluate_initial_skillFactor= True
)
a = smpModel.run(
    nb_run= 30,     
    save_path= path
)

Seed: 0 -- Time: 00m 40.02s  100 % [====================>]  Pop_size: 1.90E+02  ,  Cost: 2.04E-26  2.75E-26  0.00E+00  0.00E+00  1.45E-24  4.31E-14  0.00E+00  6.36E-04  0.00E+00  0.00E+00  ,  
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[100308, 100450, 99762, 100358, 100380, 99486, 99338, 99072, 100438, 100438]
END!
Seed: 1 -- Time: 00m 41.33s  100 % [====================>]  Pop_size: 1.90E+02  ,  Cost: 1.45E-26  2.42E-26  0.00E+00  0.00E+00  1.45E-24  4.31E-14  0.00E+00  6.36E-04  0.00E+00  0.00E+00  ,  
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[99826, 100258, 100434, 99692, 100478, 99860, 99158, 99616, 100322, 100386]
END!
Seed: 2 -- Time: 00m 2.77s    6 % [=>                  ]  Pop_size: 9.50E+02  ,  Cost: 6.55E+03  7.74E+03  7.95E+03  1.46E+01  6.04E+07  1.64E+01  4.01E+01  1.36E+04  3.15E+00  2.88E+03  ,  

AttributeError: 'model' object has no attribute 'last_pop'

In [ ]:
np.mean([model.history_cost[-1] for model in smpModel.ls_model[0].ls_model], axis = 0)

In [4]:
np.mean([model.history_cost[-1] for model in smpModel.ls_model[0].ls_model], axis = 0)

array([5.97044641e-22, 2.42607335e-26, 0.00000000e+00, 0.00000000e+00,
       9.43140297e-18, 4.35503485e-14, 0.00000000e+00, 6.36378325e-04,
       0.00000000e+00, 0.00000000e+00])

##### Complex

In [ ]:
SMP_v2 = loadModel('./RESULTS/result/WCCI22_complex/SMP_v2/8.mso', ls_tasks= t)
SMP_v2.render_smp()

In [ ]:
# complex
ls_benchmark = []
ls_IndClass = []
name_benchmark = []
path = './RESULTS/result/WCCI22_complex/SMP_v2/'

for i in range(1, 11, 1):
# for i in [3, 6, 10]:
    t, ic = WCCI22_benchmark.get_complex_benchmark(i)
    ls_benchmark.append(t)
    ls_IndClass.append(ic)
    name_benchmark.append(i)
    
compare = CompareResultBenchmark(
    path_folder="./RESULTS/result/WCCI22_complex", 
    ls_benchmark= ls_benchmark
)
compare.load_folder()

In [ ]:
compare.summarizing_compare_result(idx_main_algo= 5, min_value= 1e-6)

In [ ]:
compare.show_compare_detail(idx_main_algo=0)

##### cec17

In [ ]:
t, ic = CEC17_benchmark.get_10tasks_benchmark()

In [ ]:
# SMP_KL = loadModel('./RESULTS/result/CEC17/SMP_v2/cec17.mso', ls_tasks= t)

In [ ]:

# MFEA_model = loadModel('./RESULTS/__static__/CEC17_10tasks/MFEA_cec17.mso', ls_tasks= t)
# EBS_GA_model = loadModel('./RESULTS/__static__/CEC17_10tasks/EBS_GA_cec17.mso', ls_tasks= t)
# MaTDE_model = loadModel('./RESULTS/__static__/CEC17_10tasks/MaTDE_cec17.mso', ls_tasks= t)
# MaTGA_model = loadModel('./RESULTS/__static__/CEC17_10tasks/MaTGA_cec17.mso', ls_tasks= t)
# MTEA_AD_model = loadModel('./RESULTS/__static__/CEC17_10tasks/MTEA_AD_cec17.mso', ls_tasks= t)
# SA_model = loadModel('./RESULTS/__static__/CEC17_10tasks/SA_cec17.mso', ls_tasks= t)
# LSA_model = loadModel('./RESULTS/__static__/CEC17_10tasks/LSA_cec17.mso', ls_tasks= t)
# SMP_SBX = loadModel('./RESULTS/__static__/CEC17_10tasks/SMP_SBX.mso', ls_tasks= t)
SMP_SBX = loadModel('./RESULTS/result/CEC17_10tasks/SMP/cec17.mso', ls_tasks= t)
SMP_KL = loadModel('./RESULTS/result/CEC17_10tasks/SMP_KL/cec17.mso', ls_tasks= t)


compare = CompareModel(
    models = [
        # MFEA_model, EBS_GA_model, MaTDE_model, MaTGA_model, MTEA_AD_model, SA_model, LSA_model, 
    SMP_SBX, SMP_KL],
    label= \
        # [...] * 7 + \
            ['SMP_SBX', 'SMP + KL'],
)
compare.render(    
    shape = (2, 5),
    min_cost= 0,
    step= 100,
    yscale= 'log'
)

# SMP_newSBX.render_smp(shape= (3, 5), step = 1)
# SMP_KL.render_smp(shape= (2, 5), step = 1)
print()

30 times

In [ ]:
# smpModel = MultiTimeModel(model= SMP_MFEA)
# smpModel.compile(
#     tasks= cec17_10tasks,
#     crossover= newSBX(nc = 2, gamma= 0.4, alpha = 6),
#     # mutation= NoMutation(),
#     mutation = GMMScale(alpha = 3, lenMem= 20, default_scale= 0.5),
#     selection= ElitismSelection(random_percent= 0.),
# )
# smpModel.fit(
#     nb_generations= 10, nb_inds_each_task= 100, nb_inds_min= 20,
#     lr = 1.5, p_const_intra= 0.3, p_mutate= 0.,
#     nb_epochs_stop= 50, 
#     evaluate_initial_skillFactor= True
# )
# smpModel.run(
#     nb_run= 30,
#     save_path= './RESULTS/smpMFEA_cec17.mso'
# )

In [ ]:
# smpModel.render_history(shape = (2, 5), yscale= 'log')
# print()

In [ ]:
# smpModel.render_smp(step = 1, get_host= True)
# print()

##### GECCO20

In [ ]:
SMP_v2 = loadModel('./RESULTS/result/GECCO20/SMP_v2/3.mso', ls_tasks= t)
SMP_v2.render_smp()

In [ ]:
# gecco20
ls_benchmark = []
ls_IndClass = []
name_benchmark = []
path = './RESULTS/result/GECCO20/SMP_v2/'

for i in range(1, 11, 1):
    t, ic = WCCI22_benchmark.get_50tasks_benchmark(i)
    ls_benchmark.append(t)
    ls_IndClass.append(ic)
    name_benchmark.append(i)

In [ ]:
compare = CompareResultBenchmark(
    path_folder="./RESULTS/result/GECCO20/", 
    ls_benchmark= ls_benchmark
)
compare.load_folder()

In [ ]:
compare.summarizing_compare_result(idx_main_algo= 6, min_value= 1e-6)

In [ ]:
compare.show_compare_detail(idx_main_algo=0, min_value= 1e-6)